// Produtos disponíveis por marca — filtrados no formulário ao selecionar a marca
// "Refrigerador" → "Refrigerador / Geladeira" | "Adega" → "Adega climatizada"

export const BRAND_PRODUCTS: Record<string, string[]> = {
  "AGA": [
    "Refrigerador / Geladeira",
    "Lava-louças",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
  ],
  "Amana": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Lava-louças",
    "Lavadora",
    "Secadora",
    "Fogão",
    "Forno",
    "Cooktop",
    "Outro eletrodoméstico importado",
  ],
  "Ariston": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Lava-louças",
    "Lavadora",
    "Secadora",
    "Lava e Seca",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
    "Outro eletrodoméstico importado",
  ],
  "Asko": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Lava-louças",
    "Lavadora",
    "Secadora",
    "Forno",
    "Cooktop",
    "Coifa",
  ],
  "Bauknecht": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Lava-louças",
    "Lavadora",
    "Secadora",
    "Lava e Seca",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
    "Churrasqueira",
    "Outro eletrodoméstico importado",
  ],
  "Bertazzoni": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Lava-louças",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
    "Outro eletrodoméstico importado",
  ],
  "Best": [
    "Coifa",
  ],
  "Dacor": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Lava-louças",
    "Fogão",
    "Forno",
    "Cooktop",
    "Rangetop",
    "Coifa",
    "Outro eletrodoméstico importado",
  ],
  "DCS": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Máquina de gelo",
    "Lava-louças",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
    "Churrasqueira",
    "Outro eletrodoméstico importado",
  ],
  "Elettromec": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Máquina de gelo",
    "Lava-louças",
    "Fogão",
    "Forno",
    "Cooktop",
    "Rangetop",
    "Coifa",
    "Churrasqueira",
    "Outro eletrodoméstico importado",
  ],
  "Elica": [
    "Forno",
    "Cooktop",
    "Coifa",
  ],
  "Faber": [
    "Cooktop",
    "Coifa",
  ],
  "Fagor": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Lava-louças",
    "Lavadora",
    "Secadora",
    "Lava e Seca",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
    "Outro eletrodoméstico importado",
  ],
  "Frigidaire": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Lava-louças",
    "Lavadora",
    "Secadora",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
    "Outro eletrodoméstico importado",
  ],
  "Gaggenau": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Lava-louças",
    "Forno",
    "Cooktop",
    "Coifa",
    "Outro eletrodoméstico importado",
  ],
  "GE Monogram": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Máquina de gelo",
    "Lava-louças",
    "Fogão",
    "Forno",
    "Cooktop",
    "Rangetop",
    "Coifa",
    "Churrasqueira",
    "Outro eletrodoméstico importado",
  ],
  "Gladiator": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Outro eletrodoméstico importado",
  ],
  "Gorenje": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Lava-louças",
    "Lavadora",
    "Secadora",
    "Lava e Seca",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
    "Outro eletrodoméstico importado",
  ],
  "Hotpoint": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Lava-louças",
    "Lavadora",
    "Secadora",
    "Lava e Seca",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
    "Outro eletrodoméstico importado",
  ],
  "Ilve": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Lava-louças",
    "Fogão",
    "Forno",
    "Cooktop",
    "Rangetop",
    "Coifa",
    "Outro eletrodoméstico importado",
  ],
  "Jenn-Air": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Máquina de gelo",
    "Lava-louças",
    "Fogão",
    "Forno",
    "Cooktop",
    "Rangetop",
    "Coifa",
    "Churrasqueira",
    "Outro eletrodoméstico importado",
  ],
  "Kelvinator": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Lava-louças",
    "Lavadora",
    "Secadora",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
    "Outro eletrodoméstico importado",
  ],
  "Kenmore": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Máquina de gelo",
    "Lava-louças",
    "Lavadora",
    "Secadora",
    "Lava e Seca",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
    "Churrasqueira",
    "Outro eletrodoméstico importado",
  ],
  "KitchenAid": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Máquina de gelo",
    "Lava-louças",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
    "Churrasqueira",
    "Outro eletrodoméstico importado",
  ],
  "Liebherr": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
  ],
  "Lofra": [
    "Refrigerador / Geladeira",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
    "Outro eletrodoméstico importado",
  ],
  "Marvel": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Máquina de gelo",
  ],
  "Maytag": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Lava-louças",
    "Lavadora",
    "Secadora",
    "Lava e Seca",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
    "Outro eletrodoméstico importado",
  ],
  "Miele": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Lava-louças",
    "Lavadora",
    "Secadora",
    "Lava e Seca",
    "Fogão",
    "Forno",
    "Cooktop",
    "Rangetop",
    "Coifa",
    "Outro eletrodoméstico importado",
  ],
  "Smeg": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Lava-louças",
    "Lavadora",
    "Secadora",
    "Lava e Seca",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
    "Churrasqueira",
    "Outro eletrodoméstico importado",
  ],
  "Speed Queen": [
    "Lavadora",
    "Secadora",
    "Lava e Seca",
  ],
  "Sub Zero": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Máquina de gelo",
  ],
  "Tecno": [
    "Refrigerador / Geladeira",
    "Adega climatizada",
    "Máquina de gelo",
    "Lava-louças",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
    "Outro eletrodoméstico importado",
  ],
  "Thermador": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Lava-louças",
    "Fogão",
    "Forno",
    "Cooktop",
    "Rangetop",
    "Coifa",
    "Outro eletrodoméstico importado",
  ],
  "U-line": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Máquina de gelo",
  ],
  "Viking": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Máquina de gelo",
    "Lava-louças",
    "Fogão",
    "Forno",
    "Cooktop",
    "Rangetop",
    "Coifa",
    "Churrasqueira",
    "Outro eletrodoméstico importado",
  ],
  "Weber": [
    "Churrasqueira",
  ],
  "Whirlpool": [
    "Refrigerador / Geladeira",
    "Freezer",
    "Adega climatizada",
    "Máquina de gelo",
    "Lava-louças",
    "Lavadora",
    "Secadora",
    "Lava e Seca",
    "Fogão",
    "Forno",
    "Cooktop",
    "Coifa",
    "Outro eletrodoméstico importado",
  ],
  "Wolf": [
    "Fogão",
    "Forno",
    "Cooktop",
    "Rangetop",
    "Coifa",
    "Churrasqueira",
    "Outro eletrodoméstico importado",
  ],
};

export function getProductsForBrand(brand: string): string[] {
  return BRAND_PRODUCTS[brand] ?? [];
}
