export const PRODUCTS: string[] = [
  "Refrigerador / Geladeira",
  "Side by Side",
  "Freezer",
  "Adega climatizada",
  "Máquina de gelo",
  "Lava-louças",
  "Lavadora",
  "Secadora",
  "Lava e Seca",
  "Fogão",
  "Forno",
  "Forno de embutir",
  "Cooktop",
  "Rangetop",
  "Coifa",
  "Churrasqueira",
  "Equipamento gourmet",
  "Outro eletrodoméstico importado",
];
